### ISSUE TITLE
Correct dispatch value?

### ISSUE THREAD

**Issue by davidpham87** [macchiato-framework/macchiato-http#1]
https://github.com/macchiato-framework/macchiato-http/blob/b9d92b31c0302873dedf6fb5352e5b1440b95b1b/src/macchiato/http/request.cljc#L116

Hello, would it be possible that the dispatch value might be `:coll`? Otherwise `:string` is repeated twice.

**Comment by yogthos** [comment]
You're right, that one's a typo. Just pushed out a fix in `0.1.2`.
